spring.application.name=workload-generator

server.port=8082

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

rfp.kafka.events-topic=platform.events

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true

logging.structured.format.console=ecs
logging.level.root=INFO
logging.level.com.mustafabulu.realtimefeatureplatform=INFO
